name: Build and Release
on:
  push:
    tags:
      - '*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install Poetry
      run: |
        pip install poetry==1.3.1

    - name: Install dependencies
      run: |
        poetry install

    - name: Create Executable
      run: |
        pyinstaller --onefile png_to_webp_converter.py

    - name: Upload Executable as Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.repository.releases_url }}
        asset_path: ./dist/png_to_webp_converter.exe
        asset_name: png_to_webp_converter.exe
        asset_content_type: application/octet-stream

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install Poetry
      run: |
        pip install poetry==1.3.1

    - name: Install dependencies
      run: |
        poetry install

    - name: Create Executable
      run: |
        pyinstaller --onefile png_to_webp_converter.py

    - name: Upload Executable as Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.repository.releases_url }}
        asset_path: ./dist/png_to_webp_converter
        asset_name: png_to_webp_converter
        asset_content_type: application/octet-stream
