name: Build and Release
on:
  release:
    types:
      - created

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install Poetry
      run: |
        pip install poetry==1.3.1

    - name: Install dependencies
      run: |
        poetry install

    - name: Create Executable
      run: |
        poetry run pyinstaller --onefile png_to_webp_converter.py

    - name: Upload Executable as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: png_to_webp_converter.exe
        path: ./dist/png_to_webp_converter.exe

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install Poetry
      run: |
        pip install poetry==1.3.1

    - name: Install dependencies
      run: |
        poetry install

    - name: Create Executable
      run: |
        poetry run pyinstaller --onefile png_to_webp_converter.py

    - name: Upload Executable as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: png_to_webp_converter
        path: ./dist/png_to_webp_converter

  release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: List files in dist
        run: ls -l dist
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: dist

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*
